name: test-action
on: [push]
jobs:
  the-test-action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from the other side ğŸ™ŒğŸ¼"
      - run: echo "This is cool"
      - run: echo "This is not runnin on a ${{runner.os}} server"
      - run: echo "Branch name is ${{github.ref}}"
      - run: echo "Repository name is ${{github.repository}}"
